version: '3'

services:
  certbot:
    image: certbot/certbot
    volumes:
      - .docker/certbot/www:/var/www/certbot/
      - .docker/certbot/conf/:/etc/letsencrypt/
    depends_on:
      - web
    entrypoint: certbot certonly --webroot --webroot-path=/var/www/certbot/ --agree-tos -m contato@danielsouza.dev.br -d lan.danielsouza.dev.br -d www.lan.danielsouza.dev.br
