version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - .docker/production/nginx/conf.d/:/etc/nginx/conf.d/
      - .docker/certbot/www:/var/www/certbot/
      - .docker/certbot/conf/:/etc/nginx/ssl/
    depends_on:
      - app
    networks:
      - portal-network

networks:
  portal-network:
    driver: bridge
