version: '3'

services:
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - web
    entrypoint: certonly --webroot --webroot-path=/var/www/html --email contato@danielsouza.dev.br --agree-tos --no-eff-email --staging -d lanacos.danielsouza.dev.br  -d www.lanacos.danielsouza.dev.br

volumes:
  certbot-etc:
  certbot-var:
