version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - .docker/development/nginx/conf.d/:/etc/nginx/conf.d/
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - app
    networks:
      - portal-network

networks:
  portal-network:
    driver: bridge

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: ./resources/views/
      o: bind
