version: '3'

services:
  certbot:
    image: certbot/certbot
    volumes:
      - .docker/certbot/www:/var/www/certbot/
      - .docker/certbot/conf/:/etc/letsencrypt/
    depends_on:
      - web
    entrypoint: certbot certonly --webroot --webroot-path=/var/www/certbot/ -m contato@danielsouza.dev.br -d lanacos.danielsouza.dev.br -d www.lanacos.danielsouza.dev.br
