version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    networks:
      - portal-network
    entrypoint: ['sh', './entrypoint.prod.sh']

networks:
  portal-network:
    driver: bridge
