version: '3'

services:
  db:
    image: postgres:alpine
    ports:
      - ${PG_PORT}:${PG_PORT}
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
      TZ: 'America/Sao_Paulo'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - portal-network

networks:
  portal-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
