version: '3'

services:
  certbot:
    image: certbot/certbot
    volumes:
      - .docker/certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
    depends_on:
      - web
    entrypoint: certbot certonly --webroot --webroot-path /var/www/certbot/ -d lanacos.danielsouza.dev.br
