version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    networks:
      - portal-network

  web:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - .docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - portal-network

  db:
    image: postgres:alpine
    ports:
      - ${PG_PORT}:${PG_PORT}
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
      TZ: 'America/Sao_Paulo'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - portal-network

#Docker Networks
networks:
  portal-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
